services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/mlruns
      --allowed-hosts "*"
    ports:
      - "5000:5000"
    volumes:
      - mlruns:/mlflow/mlruns

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      mlflow:
        condition: service_started
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - mlruns:/mlflow/mlruns

  trainer:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    depends_on:
      mlflow:
        condition: service_started
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - mlruns:/mlflow/mlruns

volumes:
  mlruns: